### ISSUE TITLE
每天早上匯報當日工寮活動的 Telegram Bot

### ISSUE THREAD

**Issue by irvin** [moztw/_good-holes-to-jump#22]
如果有一個 bot 每天早上匯報當天工寮有什麼活動，應該會蠻實用的。
可以從行事曆去取活動資料：
 https://calendar.google.com/calendar/embed?src=3fs8qeakm6ij88hibpb5bsg3mc%40group.calendar.google.com

**Comment by Sea-n** [comment]
這幾天測試都有正常運作，應該是沒問題了

**Comment by irvin** [comment]
Cool
